apiVersion: v1
kind: Secret
metadata:
  name: odh-tec-env
type: Opaque
data:
  AWS_S3_ENDPOINT: <base 64 encoded s3 storage endpoint>
  AWS_ACCESS_KEY_ID: bWluaW8tcm9vdA==
  AWS_SECRET_ACCESS_KEY: c3VyZS1zZWNyZXQ=
  AWS_DEFAULT_REGION: bWFpbm8=
  AWS_S3_BUCKET: bW9kZWxz
  HF_TOKEN: <base 64 encoded hugging face token>
  MAX_CONCURRENT_TRANSFERS: MQ==
