apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-kueue-operator-
  name: openshift-kueue-operator
  namespace: openshift-kueue-operator
spec:
  upgradeStrategy: Default